USE DATABASE NETFLIX;
    USE SCHEMA PUBLIC;

TRUNCATE TABLE NETFLIX.PUBLIC.TITLE_COUNTRY;

INSERT INTO NETFLIX.PUBLIC.TITLE_COUNTRY (show_id, country_id)
SELECT DISTINCT
    f.SHOW_ID,
    d.country_id
FROM
    NETFLIX.PUBLIC.FULLINFO f
JOIN
    NETFLIX.PUBLIC.COUNTRIES d ON TRIM(LOWER(f."COUNTRY")) = TRIM(LOWER(d.country))
WHERE
    f."COUNTRY" IS NOT NULL
    AND f."COUNTRY" != 'Unknown'
    AND f."COUNTRY" != 'null'
    AND NOT EXISTS (
        SELECT 1 FROM NETFLIX.PUBLIC.TITLE_COUNTRY td
        WHERE td.show_id = f.SHOW_ID
        AND td.country_id = d.country_id
    );