
USE DATABASE NETFLIX;
    USE SCHEMA PUBLIC;

TRUNCATE TABLE NETFLIX.PUBLIC.TITLE_GENRE;

INSERT INTO NETFLIX.PUBLIC.TITLE_GENRE (show_id, genre_id)
SELECT DISTINCT
    f.SHOW_ID,
    d.genre_id
FROM
    NETFLIX.PUBLIC.FULLINFO f
JOIN
    NETFLIX.PUBLIC.GENRES d ON TRIM(LOWER(f."GENRE")) = TRIM(LOWER(d.genre))
WHERE
    f."GENRE" IS NOT NULL
    AND f."GENRE" != 'Unknown'
    AND f."GENRE" != 'null'
    AND NOT EXISTS (
        SELECT 1 FROM NETFLIX.PUBLIC.TITLE_GENRE td
        WHERE td.show_id = f.SHOW_ID
        AND td.genre_id = d.genre_id
    );