USE DATABASE NETFLIX;
    USE SCHEMA PUBLIC;

TRUNCATE TABLE NETFLIX.PUBLIC.TITLE_DIRECTOR;

INSERT INTO NETFLIX.PUBLIC.TITLE_DIRECTOR (show_id, director_id)
SELECT DISTINCT
    f.SHOW_ID,
    d.director_id
FROM
    NETFLIX.PUBLIC.FULLINFO f
JOIN
    NETFLIX.PUBLIC.DIRECTORS d ON TRIM(LOWER(f."DIRECTOR")) = TRIM(LOWER(d.director))
WHERE
    f."DIRECTOR" IS NOT NULL
    AND f."DIRECTOR" != 'Unknown'
    AND f."DIRECTOR" != 'null'
    AND NOT EXISTS (
        SELECT 1 FROM NETFLIX.PUBLIC.TITLE_DIRECTOR td
        WHERE td.show_id = f.SHOW_ID
        AND td.director_id = d.director_id
    );